branches:
  only:
    - integration
    - /-ci$/

dist: trusty
sudo: required

language: c

services:
  - docker

matrix:
  include:
    - env: PGB_CI="test --vm=f30 --param=no-package --param=c-only"
    - env: PGB_CI="test --vm=co7 --param=no-package --param=module=mock --param=test=all"
    - env: PGB_CI="test --vm=co6 --param=no-package --param=module=mock --param=test=all"
    - env: PGB_CI="test --vm=u12 --param=no-package --param=module=mock --param=test=all"
    - env: PGB_CI="test --vm=u18 --param=no-package --param=module=mock --param=test=all"

install:
  - umask 0022 && cd ~ && pwd && whoami && umask && groups
  - df -Th && top -bn1

script:
  - ${TRAVIS_BUILD_DIR?}/test/travis.pl ${PGB_CI?}
