branches:
  only:
    - integration
    - /-ci$/

dist: trusty
sudo: required

language: c

services:
  - docker

env:
  - PGB_CI="doc"
  - PGB_CI="--vm=u18 test"
  - PGB_CI="--vm=co6 test"
  - PGB_CI="--vm=co7 test"
  - PGB_CI="--vm=u12 test"

before_install:
  - sudo apt-get -qq update && sudo apt-get install libxml-checker-perl libdbd-pg-perl libyaml-libyaml-perl python-pip lcov libperl-dev
  - |
    # Install & Configure AWS CLI
    pip install --upgrade --user awscli
    aws configure set region us-east-1
    aws configure set aws_access_key_id accessKey1
    aws configure set aws_secret_access_key verySecretKey1
    aws help --version
    aws configure list

install:
  - |
    # User Configuration
    sudo adduser --ingroup=${USER?} --uid=5001 --disabled-password --gecos "" pgbackrest
    umask 0022
    cd ~ && pwd && whoami && umask && groups
    mv ${TRAVIS_BUILD_DIR?} pgbackrest
    rm -rf ${TRAVIS_BUILD_DIR?}

script:
  - pgbackrest/test/travis.pl ${PGB_CI?}
