branches:
  only:
    - integration
    - /-ci$/

dist: trusty
sudo: required

language: c

services:
  - docker

matrix:
  include:
    - env: PGB_CI="--vm=u12 test"
    - env: PGB_CI="--vm=f30 test"
    - env: PGB_CI="--vm=co6 test"
    - env: PGB_CI="--vm=u18 test"
    - env: PGB_CI="--vm=u18 doc"
    - env: PGB_CI="--vm=co7 test"
    - dist: bionic
      env: PGB_CI="--vm=none test"
      services:
    - env: PGB_CI="--vm=co6 doc"
    - env: PGB_CI="--vm=co7 doc"

install:
  - umask 0022
  - cd ~ && pwd && whoami && umask && groups

script:
  - ${TRAVIS_BUILD_DIR?}/test/travis.pl ${PGB_CI?}
