branches:
  only:
    - integration
    - /-ci$/

dist: trusty
sudo: required

language: c

services:
  - docker

matrix:
  include:
    - env: PGB_CI="--vm=f30 test"

install:
  - umask 0022
  - cd ~ && pwd && whoami && umask && groups

script:
  - ${TRAVIS_BUILD_DIR?}/test/travis.pl ${PGB_CI?}
